// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity_items (session_id, type, description, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, type, description, metadata, created_at
`

type CreateActivityParams struct {
	SessionID   uuid.UUID `json:"session_id"`
	Type        string    `json:"type"`
	Description string    `json:"description"`
	Metadata    []byte    `json:"metadata"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.SessionID,
		arg.Type,
		arg.Description,
		arg.Metadata,
	)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, session_id, type, description, metadata, created_at FROM activity_items
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListActivitiesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ActivityItem, error) {
	rows, err := q.db.Query(ctx, listActivities, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityItem{}
	for rows.Next() {
		var i ActivityItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
