// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
)

const getDeuceAgent = `-- name: GetDeuceAgent :one
SELECT id, system_prompt FROM agents LIMIT 1
`

// The agents table holds exactly one row — the built-in "deuce" agent
// (migration 013; id + system_prompt only, identity renders from constants).
// Single-row read backs GET /api/agent and the runtime's launch-time
// system-prompt fetch.
func (q *Queries) GetDeuceAgent(ctx context.Context) (Agent, error) {
	row := q.db.QueryRow(ctx, getDeuceAgent)
	var i Agent
	err := row.Scan(&i.ID, &i.SystemPrompt)
	return i, err
}

const updateDeuceSystemPrompt = `-- name: UpdateDeuceSystemPrompt :one
UPDATE agents SET system_prompt = $1 RETURNING id, system_prompt
`

func (q *Queries) UpdateDeuceSystemPrompt(ctx context.Context, systemPrompt string) (Agent, error) {
	row := q.db.QueryRow(ctx, updateDeuceSystemPrompt, systemPrompt)
	var i Agent
	err := row.Scan(&i.ID, &i.SystemPrompt)
	return i, err
}
