// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAgent = `-- name: GetAgent :one
SELECT id, name, role, color, color_muted, provider, model, description FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Color,
		&i.ColorMuted,
		&i.Provider,
		&i.Model,
		&i.Description,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, role, color, color_muted, provider, model, description FROM agents ORDER BY name
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Color,
			&i.ColorMuted,
			&i.Provider,
			&i.Model,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
