// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (session_id, author_id, author_type, content, expandable_content, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, author_id, author_type, content, expandable_content, status, created_at
`

type CreateMessageParams struct {
	SessionID         uuid.UUID `json:"session_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	AuthorType        string    `json:"author_type"`
	Content           string    `json:"content"`
	ExpandableContent []byte    `json:"expandable_content"`
	Status            string    `json:"status"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SessionID,
		arg.AuthorID,
		arg.AuthorType,
		arg.Content,
		arg.ExpandableContent,
		arg.Status,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AuthorID,
		&i.AuthorType,
		&i.Content,
		&i.ExpandableContent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, author_id, author_type, content, expandable_content, status, created_at FROM messages
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMessagesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AuthorID,
			&i.AuthorType,
			&i.Content,
			&i.ExpandableContent,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT messages.id, messages.session_id, messages.author_id, messages.author_type, messages.content, messages.expandable_content, messages.status, messages.created_at FROM messages
WHERE messages.session_id = $1
  AND messages.created_at < (SELECT m2.created_at FROM messages m2 WHERE m2.id = $2)
ORDER BY messages.created_at DESC
LIMIT $3
`

type ListMessagesBeforeParams struct {
	SessionID uuid.UUID `json:"session_id"`
	ID        uuid.UUID `json:"id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.SessionID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AuthorID,
			&i.AuthorType,
			&i.Content,
			&i.ExpandableContent,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
