// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityItem struct {
	ID          uuid.UUID `json:"id"`
	SessionID   uuid.UUID `json:"session_id"`
	Type        string    `json:"type"`
	Description string    `json:"description"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
}

type Agent struct {
	ID           uuid.UUID `json:"id"`
	SystemPrompt string    `json:"system_prompt"`
}

type Message struct {
	ID                uuid.UUID `json:"id"`
	SessionID         uuid.UUID `json:"session_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	AuthorType        string    `json:"author_type"`
	Content           string    `json:"content"`
	ExpandableContent []byte    `json:"expandable_content"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
}

type Project struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	RepoUrl string    `json:"repo_url"`
	TeamID  uuid.UUID `json:"team_id"`
}

type Session struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	ProjectID       uuid.UUID `json:"project_id"`
	Status          string    `json:"status"`
	WorkspaceStatus string    `json:"workspace_status"`
	PlanContent     string    `json:"plan_content"`
	CreatedAt       time.Time `json:"created_at"`
	LastActivityAt  time.Time `json:"last_activity_at"`
	RepoUrl         string    `json:"repo_url"`
	Description     string    `json:"description"`
}

type SessionEventSeq struct {
	SessionID uuid.UUID `json:"session_id"`
	NextSeq   int64     `json:"next_seq"`
}

type SessionMember struct {
	SessionID  uuid.UUID `json:"session_id"`
	UserID     uuid.UUID `json:"user_id"`
	LastReadAt time.Time `json:"last_read_at"`
}

type Task struct {
	ID                     uuid.UUID   `json:"id"`
	SessionID              uuid.UUID   `json:"session_id"`
	RequestedBy            pgtype.UUID `json:"requested_by"`
	AnchorMessageID        pgtype.UUID `json:"anchor_message_id"`
	Prompt                 string      `json:"prompt"`
	State                  string      `json:"state"`
	Seq                    int64       `json:"seq"`
	PendingQuestion        string      `json:"pending_question"`
	Reply                  string      `json:"reply"`
	Work                   []byte      `json:"work"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedAt              time.Time   `json:"updated_at"`
	PendingQuestionKind    string      `json:"pending_question_kind"`
	PendingQuestionOptions []string    `json:"pending_question_options"`
}

type TaskAction struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	CallID    string    `json:"call_id"`
	Seq       int64     `json:"seq"`
	Tool      string    `json:"tool"`
	Arg       string    `json:"arg"`
	Note      string    `json:"note"`
	Text      string    `json:"text"`
	Stat      string    `json:"stat"`
	Diff      []byte    `json:"diff"`
	Out       []byte    `json:"out"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	IsDefault bool      `json:"is_default"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Avatar    string    `json:"avatar"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type UserSshKey struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Label       string             `json:"label"`
	PublicKey   string             `json:"public_key"`
	Fingerprint string             `json:"fingerprint"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}
