// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityItem struct {
	ID          uuid.UUID   `json:"id"`
	SessionID   uuid.UUID   `json:"session_id"`
	Type        string      `json:"type"`
	Description string      `json:"description"`
	AgentID     pgtype.UUID `json:"agent_id"`
	Metadata    []byte      `json:"metadata"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Agent struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	Color        string             `json:"color"`
	ColorMuted   string             `json:"color_muted"`
	Provider     string             `json:"provider"`
	Model        string             `json:"model"`
	Description  string             `json:"description"`
	SystemPrompt string             `json:"system_prompt"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type Message struct {
	ID                uuid.UUID `json:"id"`
	SessionID         uuid.UUID `json:"session_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	AuthorType        string    `json:"author_type"`
	Content           string    `json:"content"`
	ExpandableContent []byte    `json:"expandable_content"`
	Mentions          []string  `json:"mentions"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
}

type Project struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	RepoUrl string    `json:"repo_url"`
	TeamID  uuid.UUID `json:"team_id"`
}

type Session struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	ProjectID       uuid.UUID `json:"project_id"`
	Status          string    `json:"status"`
	WorkspaceStatus string    `json:"workspace_status"`
	PlanContent     string    `json:"plan_content"`
	CreatedAt       time.Time `json:"created_at"`
	LastActivityAt  time.Time `json:"last_activity_at"`
	RepoUrl         string    `json:"repo_url"`
	Description     string    `json:"description"`
}

type SessionAgent struct {
	SessionID       uuid.UUID `json:"session_id"`
	AgentID         uuid.UUID `json:"agent_id"`
	Status          string    `json:"status"`
	ClaudeSessionID string    `json:"claude_session_id"`
}

type SessionMember struct {
	SessionID  uuid.UUID `json:"session_id"`
	UserID     uuid.UUID `json:"user_id"`
	LastReadAt time.Time `json:"last_read_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	Avatar           string             `json:"avatar"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	ForgeUserID      pgtype.Int8        `json:"forge_user_id"`
	ForgeFirstSeenAt pgtype.Timestamptz `json:"forge_first_seen_at"`
}
