// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patches.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatch = `-- name: CreatePatch :one
INSERT INTO patches (
    session_id,
    producing_message_id,
    parent_patch_id,
    origin_type,
    workspace_sha,
    committed_sha,
    hunks,
    file_count,
    hunk_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, producing_message_id, parent_patch_id, origin_type, workspace_sha, committed_sha, hunks, file_count, hunk_count, created_at
`

type CreatePatchParams struct {
	SessionID          uuid.UUID   `json:"session_id"`
	ProducingMessageID pgtype.UUID `json:"producing_message_id"`
	ParentPatchID      pgtype.UUID `json:"parent_patch_id"`
	OriginType         string      `json:"origin_type"`
	WorkspaceSha       string      `json:"workspace_sha"`
	CommittedSha       pgtype.Text `json:"committed_sha"`
	Hunks              []byte      `json:"hunks"`
	FileCount          int32       `json:"file_count"`
	HunkCount          int32       `json:"hunk_count"`
}

func (q *Queries) CreatePatch(ctx context.Context, arg CreatePatchParams) (Patch, error) {
	row := q.db.QueryRow(ctx, createPatch,
		arg.SessionID,
		arg.ProducingMessageID,
		arg.ParentPatchID,
		arg.OriginType,
		arg.WorkspaceSha,
		arg.CommittedSha,
		arg.Hunks,
		arg.FileCount,
		arg.HunkCount,
	)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProducingMessageID,
		&i.ParentPatchID,
		&i.OriginType,
		&i.WorkspaceSha,
		&i.CommittedSha,
		&i.Hunks,
		&i.FileCount,
		&i.HunkCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPatchBySessionAndID = `-- name: GetPatchBySessionAndID :one
SELECT id, session_id, producing_message_id, parent_patch_id, origin_type, workspace_sha, committed_sha, hunks, file_count, hunk_count, created_at FROM patches
WHERE session_id = $1 AND id = $2
`

type GetPatchBySessionAndIDParams struct {
	SessionID uuid.UUID `json:"session_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetPatchBySessionAndID(ctx context.Context, arg GetPatchBySessionAndIDParams) (Patch, error) {
	row := q.db.QueryRow(ctx, getPatchBySessionAndID, arg.SessionID, arg.ID)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProducingMessageID,
		&i.ParentPatchID,
		&i.OriginType,
		&i.WorkspaceSha,
		&i.CommittedSha,
		&i.Hunks,
		&i.FileCount,
		&i.HunkCount,
		&i.CreatedAt,
	)
	return i, err
}

const listPatchesBySession = `-- name: ListPatchesBySession :many
SELECT id, session_id, producing_message_id, parent_patch_id, origin_type, workspace_sha, committed_sha, hunks, file_count, hunk_count, created_at FROM patches
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPatchesBySessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListPatchesBySession(ctx context.Context, arg ListPatchesBySessionParams) ([]Patch, error) {
	rows, err := q.db.Query(ctx, listPatchesBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProducingMessageID,
			&i.ParentPatchID,
			&i.OriginType,
			&i.WorkspaceSha,
			&i.CommittedSha,
			&i.Hunks,
			&i.FileCount,
			&i.HunkCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
