// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSessionAgent = `-- name: AddSessionAgent :exec
INSERT INTO session_agents (session_id, agent_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSessionAgentParams struct {
	SessionID uuid.UUID `json:"session_id"`
	AgentID   uuid.UUID `json:"agent_id"`
}

func (q *Queries) AddSessionAgent(ctx context.Context, arg AddSessionAgentParams) error {
	_, err := q.db.Exec(ctx, addSessionAgent, arg.SessionID, arg.AgentID)
	return err
}

const addSessionMember = `-- name: AddSessionMember :exec
INSERT INTO session_members (session_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSessionMemberParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddSessionMember(ctx context.Context, arg AddSessionMemberParams) error {
	_, err := q.db.Exec(ctx, addSessionMember, arg.SessionID, arg.UserID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (name, description, project_id, repo_url, status, workspace_status, plan_content)
VALUES ($1, $2, $3, $4, 'active', 'starting', '')
RETURNING id, name, project_id, status, workspace_status, plan_content, created_at, last_activity_at, repo_url, description
`

type CreateSessionParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ProjectID   uuid.UUID `json:"project_id"`
	RepoUrl     string    `json:"repo_url"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Name,
		arg.Description,
		arg.ProjectID,
		arg.RepoUrl,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Status,
		&i.WorkspaceStatus,
		&i.PlanContent,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.RepoUrl,
		&i.Description,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, name, project_id, status, workspace_status, plan_content, created_at, last_activity_at, repo_url, description FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Status,
		&i.WorkspaceStatus,
		&i.PlanContent,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.RepoUrl,
		&i.Description,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*)::int FROM messages m
JOIN session_members sm ON m.session_id = sm.session_id AND sm.user_id = $2
WHERE m.session_id = $1
AND m.created_at > sm.last_read_at
`

type GetUnreadCountParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, arg.SessionID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listSessionAgents = `-- name: ListSessionAgents :many
SELECT a.id, a.name, a.role, a.color, a.color_muted, a.provider, a.model, a.description, a.system_prompt, a.deleted_at, a.created_at, a.updated_at, sa.status as agent_status FROM agents a
JOIN session_agents sa ON a.id = sa.agent_id
WHERE sa.session_id = $1
ORDER BY a.name
`

type ListSessionAgentsRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	Color        string             `json:"color"`
	ColorMuted   string             `json:"color_muted"`
	Provider     string             `json:"provider"`
	Model        string             `json:"model"`
	Description  string             `json:"description"`
	SystemPrompt string             `json:"system_prompt"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	AgentStatus  string             `json:"agent_status"`
}

func (q *Queries) ListSessionAgents(ctx context.Context, sessionID uuid.UUID) ([]ListSessionAgentsRow, error) {
	rows, err := q.db.Query(ctx, listSessionAgents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionAgentsRow{}
	for rows.Next() {
		var i ListSessionAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Color,
			&i.ColorMuted,
			&i.Provider,
			&i.Model,
			&i.Description,
			&i.SystemPrompt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMembers = `-- name: ListSessionMembers :many
SELECT u.id, u.name, u.email, u.avatar, u.status, u.created_at, u.forge_user_id, u.forge_first_seen_at FROM users u
JOIN session_members sm ON u.id = sm.user_id
WHERE sm.session_id = $1
ORDER BY u.name
`

func (q *Queries) ListSessionMembers(ctx context.Context, sessionID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listSessionMembers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Avatar,
			&i.Status,
			&i.CreatedAt,
			&i.ForgeUserID,
			&i.ForgeFirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT s.id, s.name, s.project_id, s.status, s.workspace_status, s.plan_content, s.created_at, s.last_activity_at, s.repo_url, s.description FROM sessions s
JOIN session_members sm ON s.id = sm.session_id
WHERE sm.user_id = $1
ORDER BY s.last_activity_at DESC
`

func (q *Queries) ListSessionsForUser(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.Status,
			&i.WorkspaceStatus,
			&i.PlanContent,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.RepoUrl,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionRead = `-- name: MarkSessionRead :exec
UPDATE session_members SET last_read_at = now()
WHERE session_id = $1 AND user_id = $2
`

type MarkSessionReadParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkSessionRead(ctx context.Context, arg MarkSessionReadParams) error {
	_, err := q.db.Exec(ctx, markSessionRead, arg.SessionID, arg.UserID)
	return err
}

const removeAllSessionAgents = `-- name: RemoveAllSessionAgents :exec
DELETE FROM session_agents WHERE session_id = $1
`

func (q *Queries) RemoveAllSessionAgents(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllSessionAgents, sessionID)
	return err
}

const updateSessionAgentStatus = `-- name: UpdateSessionAgentStatus :exec
UPDATE session_agents SET status = $3
WHERE session_id = $1 AND agent_id = $2
`

type UpdateSessionAgentStatusParams struct {
	SessionID uuid.UUID `json:"session_id"`
	AgentID   uuid.UUID `json:"agent_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateSessionAgentStatus(ctx context.Context, arg UpdateSessionAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionAgentStatus, arg.SessionID, arg.AgentID, arg.Status)
	return err
}

const updateSessionDescription = `-- name: UpdateSessionDescription :one
UPDATE sessions SET description = $2 WHERE id = $1 RETURNING id, name, project_id, status, workspace_status, plan_content, created_at, last_activity_at, repo_url, description
`

type UpdateSessionDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateSessionDescription(ctx context.Context, arg UpdateSessionDescriptionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionDescription, arg.ID, arg.Description)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Status,
		&i.WorkspaceStatus,
		&i.PlanContent,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.RepoUrl,
		&i.Description,
	)
	return i, err
}

const updateSessionLastActivity = `-- name: UpdateSessionLastActivity :exec
UPDATE sessions SET last_activity_at = now() WHERE id = $1
`

func (q *Queries) UpdateSessionLastActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastActivity, id)
	return err
}

const updateSessionPlan = `-- name: UpdateSessionPlan :one
UPDATE sessions SET plan_content = $2 WHERE id = $1 RETURNING id, name, project_id, status, workspace_status, plan_content, created_at, last_activity_at, repo_url, description
`

type UpdateSessionPlanParams struct {
	ID          uuid.UUID `json:"id"`
	PlanContent string    `json:"plan_content"`
}

func (q *Queries) UpdateSessionPlan(ctx context.Context, arg UpdateSessionPlanParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionPlan, arg.ID, arg.PlanContent)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Status,
		&i.WorkspaceStatus,
		&i.PlanContent,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.RepoUrl,
		&i.Description,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions SET status = $2 WHERE id = $1 RETURNING id, name, project_id, status, workspace_status, plan_content, created_at, last_activity_at, repo_url, description
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Status,
		&i.WorkspaceStatus,
		&i.PlanContent,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.RepoUrl,
		&i.Description,
	)
	return i, err
}

const updateSessionWorkspaceStatus = `-- name: UpdateSessionWorkspaceStatus :one
UPDATE sessions SET workspace_status = $2 WHERE id = $1 RETURNING id, name, project_id, status, workspace_status, plan_content, created_at, last_activity_at, repo_url, description
`

type UpdateSessionWorkspaceStatusParams struct {
	ID              uuid.UUID `json:"id"`
	WorkspaceStatus string    `json:"workspace_status"`
}

func (q *Queries) UpdateSessionWorkspaceStatus(ctx context.Context, arg UpdateSessionWorkspaceStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionWorkspaceStatus, arg.ID, arg.WorkspaceStatus)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Status,
		&i.WorkspaceStatus,
		&i.PlanContent,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.RepoUrl,
		&i.Description,
	)
	return i, err
}
