// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allocateEventSeq = `-- name: AllocateEventSeq :one
INSERT INTO session_event_seq (session_id, next_seq)
VALUES ($1, 2)
ON CONFLICT (session_id)
DO UPDATE SET next_seq = session_event_seq.next_seq + 1
RETURNING (next_seq - 1)::bigint AS seq
`

// Allocate the next per-session event seq, creating the counter row on first
// use. Returns the allocated value; the stored next_seq is left pointing at the
// following value. Run inside the same tx as the state write it stamps (KTD6).
func (q *Queries) AllocateEventSeq(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, allocateEventSeq, sessionID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const appendAction = `-- name: AppendAction :exec
INSERT INTO task_actions (task_id, call_id, seq, tool, arg, status)
VALUES ($1, $2, $3, $4, $5, 'started')
ON CONFLICT (task_id, call_id) DO NOTHING
`

type AppendActionParams struct {
	TaskID uuid.UUID `json:"task_id"`
	CallID string    `json:"call_id"`
	Seq    int64     `json:"seq"`
	Tool   string    `json:"tool"`
	Arg    string    `json:"arg"`
}

// Idempotent on (task_id, call_id): a replayed tool-start after re-attach is a
// no-op (KTD13).
func (q *Queries) AppendAction(ctx context.Context, arg AppendActionParams) error {
	_, err := q.db.Exec(ctx, appendAction,
		arg.TaskID,
		arg.CallID,
		arg.Seq,
		arg.Tool,
		arg.Arg,
	)
	return err
}

const completeAction = `-- name: CompleteAction :exec
UPDATE task_actions
SET status = $3, text = $4, out = $5, diff = $6, stat = $7, seq = $8
WHERE task_id = $1 AND call_id = $2
`

type CompleteActionParams struct {
	TaskID uuid.UUID `json:"task_id"`
	CallID string    `json:"call_id"`
	Status string    `json:"status"`
	Text   string    `json:"text"`
	Out    []byte    `json:"out"`
	Diff   []byte    `json:"diff"`
	Stat   string    `json:"stat"`
	Seq    int64     `json:"seq"`
}

func (q *Queries) CompleteAction(ctx context.Context, arg CompleteActionParams) error {
	_, err := q.db.Exec(ctx, completeAction,
		arg.TaskID,
		arg.CallID,
		arg.Status,
		arg.Text,
		arg.Out,
		arg.Diff,
		arg.Stat,
		arg.Seq,
	)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (session_id, requested_by, anchor_message_id, prompt, state, seq)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, requested_by, anchor_message_id, prompt, state, seq, pending_question, reply, work, created_at, updated_at, pending_question_kind, pending_question_options
`

type CreateTaskParams struct {
	SessionID       uuid.UUID   `json:"session_id"`
	RequestedBy     pgtype.UUID `json:"requested_by"`
	AnchorMessageID pgtype.UUID `json:"anchor_message_id"`
	Prompt          string      `json:"prompt"`
	State           string      `json:"state"`
	Seq             int64       `json:"seq"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.SessionID,
		arg.RequestedBy,
		arg.AnchorMessageID,
		arg.Prompt,
		arg.State,
		arg.Seq,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.AnchorMessageID,
		&i.Prompt,
		&i.State,
		&i.Seq,
		&i.PendingQuestion,
		&i.Reply,
		&i.Work,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingQuestionKind,
		&i.PendingQuestionOptions,
	)
	return i, err
}

const failStuckTasks = `-- name: FailStuckTasks :exec
UPDATE tasks SET state = 'failed', updated_at = now() WHERE state IN ('running', 'awaiting_input')
`

// Boot recovery (KTD10): tasks left running/awaiting_input by a crash are
// reconciled to failed before the scheduler starts. (The pre-013 companion
// ClearStuckPiSessions is gone with session_agents.pi_session_id — Pi
// resume-across-restart was never wired up, so there is no session id to
// clear; every relaunch starts a fresh Pi process.)
func (q *Queries) FailStuckTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, failStuckTasks)
	return err
}

const finishTask = `-- name: FinishTask :exec
UPDATE tasks SET state = $2, reply = $3, work = $4, pending_question = '', pending_question_kind = '', pending_question_options = '{}', seq = $5, updated_at = now() WHERE id = $1
`

type FinishTaskParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
	Reply string    `json:"reply"`
	Work  []byte    `json:"work"`
	Seq   int64     `json:"seq"`
}

func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) error {
	_, err := q.db.Exec(ctx, finishTask,
		arg.ID,
		arg.State,
		arg.Reply,
		arg.Work,
		arg.Seq,
	)
	return err
}

const forceResolveOpenActions = `-- name: ForceResolveOpenActions :exec
UPDATE task_actions SET status = 'interrupted' WHERE task_id = $1 AND status = 'started'
`

// On task terminal, any still-'started' action is forced terminal so the
// snapshot can never show a perpetually-spinning action (KTD: orphan resolve).
func (q *Queries) ForceResolveOpenActions(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, forceResolveOpenActions, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, session_id, requested_by, anchor_message_id, prompt, state, seq, pending_question, reply, work, created_at, updated_at, pending_question_kind, pending_question_options FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.AnchorMessageID,
		&i.Prompt,
		&i.State,
		&i.Seq,
		&i.PendingQuestion,
		&i.Reply,
		&i.Work,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingQuestionKind,
		&i.PendingQuestionOptions,
	)
	return i, err
}

const isSessionMember = `-- name: IsSessionMember :one
SELECT EXISTS (
    SELECT 1 FROM session_members WHERE session_id = $1 AND user_id = $2
) AS is_member
`

type IsSessionMemberParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// Membership gate for steering + snapshot authorization (KTD14).
func (q *Queries) IsSessionMember(ctx context.Context, arg IsSessionMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionMember, arg.SessionID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listSessionTaskActions = `-- name: ListSessionTaskActions :many
SELECT ta.id, ta.task_id, ta.call_id, ta.seq, ta.tool, ta.arg, ta.note, ta.text, ta.stat, ta.diff, ta.out, ta.status, ta.created_at FROM task_actions ta
JOIN tasks t ON t.id = ta.task_id
WHERE t.session_id = $1
ORDER BY ta.task_id, ta.seq ASC
`

// All actions for a session's tasks, for the snapshot read (joined to tasks so
// it is scoped by session in one query).
func (q *Queries) ListSessionTaskActions(ctx context.Context, sessionID uuid.UUID) ([]TaskAction, error) {
	rows, err := q.db.Query(ctx, listSessionTaskActions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAction{}
	for rows.Next() {
		var i TaskAction
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CallID,
			&i.Seq,
			&i.Tool,
			&i.Arg,
			&i.Note,
			&i.Text,
			&i.Stat,
			&i.Diff,
			&i.Out,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTasks = `-- name: ListSessionTasks :many
SELECT id, session_id, requested_by, anchor_message_id, prompt, state, seq, pending_question, reply, work, created_at, updated_at, pending_question_kind, pending_question_options FROM tasks WHERE session_id = $1 ORDER BY created_at ASC
`

// A session's tasks in creation order — drives queue-position derivation (R12)
// and promotion (R13) in the scheduler, plus the snapshot read.
func (q *Queries) ListSessionTasks(ctx context.Context, sessionID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSessionTasks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RequestedBy,
			&i.AnchorMessageID,
			&i.Prompt,
			&i.State,
			&i.Seq,
			&i.PendingQuestion,
			&i.Reply,
			&i.Work,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PendingQuestionKind,
			&i.PendingQuestionOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActions = `-- name: ListTaskActions :many
SELECT id, task_id, call_id, seq, tool, arg, note, text, stat, diff, out, status, created_at FROM task_actions WHERE task_id = $1 ORDER BY seq ASC, created_at ASC
`

func (q *Queries) ListTaskActions(ctx context.Context, taskID uuid.UUID) ([]TaskAction, error) {
	rows, err := q.db.Query(ctx, listTaskActions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAction{}
	for rows.Next() {
		var i TaskAction
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CallID,
			&i.Seq,
			&i.Tool,
			&i.Arg,
			&i.Note,
			&i.Text,
			&i.Stat,
			&i.Diff,
			&i.Out,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peekEventSeq = `-- name: PeekEventSeq :one
SELECT COALESCE((SELECT next_seq - 1 FROM session_event_seq WHERE session_id = $1), 0)::bigint AS seq
`

// Highest allocated seq for a session (next_seq - 1), or 0 if none. Used as the
// snapshot's latest_seq lower bound and to seed any in-memory cache on boot.
func (q *Queries) PeekEventSeq(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, peekEventSeq, sessionID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const resolveTaskInput = `-- name: ResolveTaskInput :exec
UPDATE tasks SET state = 'running', pending_question = '', pending_question_kind = '', pending_question_options = '{}', seq = $2, updated_at = now() WHERE id = $1
`

type ResolveTaskInputParams struct {
	ID  uuid.UUID `json:"id"`
	Seq int64     `json:"seq"`
}

func (q *Queries) ResolveTaskInput(ctx context.Context, arg ResolveTaskInputParams) error {
	_, err := q.db.Exec(ctx, resolveTaskInput, arg.ID, arg.Seq)
	return err
}

const setTaskAwaitingInput = `-- name: SetTaskAwaitingInput :exec
UPDATE tasks SET state = 'awaiting_input', pending_question = $2, pending_question_kind = $3, pending_question_options = $4, seq = $5, updated_at = now() WHERE id = $1
`

type SetTaskAwaitingInputParams struct {
	ID                     uuid.UUID `json:"id"`
	PendingQuestion        string    `json:"pending_question"`
	PendingQuestionKind    string    `json:"pending_question_kind"`
	PendingQuestionOptions []string  `json:"pending_question_options"`
	Seq                    int64     `json:"seq"`
}

func (q *Queries) SetTaskAwaitingInput(ctx context.Context, arg SetTaskAwaitingInputParams) error {
	_, err := q.db.Exec(ctx, setTaskAwaitingInput,
		arg.ID,
		arg.PendingQuestion,
		arg.PendingQuestionKind,
		arg.PendingQuestionOptions,
		arg.Seq,
	)
	return err
}

const updateTaskState = `-- name: UpdateTaskState :exec
UPDATE tasks SET state = $2, seq = $3, updated_at = now() WHERE id = $1
`

type UpdateTaskStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
	Seq   int64     `json:"seq"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error {
	_, err := q.db.Exec(ctx, updateTaskState, arg.ID, arg.State, arg.Seq)
	return err
}
