// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_ssh_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserSSHKey = `-- name: CreateUserSSHKey :one
INSERT INTO user_ssh_keys (user_id, label, public_key, fingerprint)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, label, public_key, fingerprint, created_at, last_used_at
`

type CreateUserSSHKeyParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Label       string    `json:"label"`
	PublicKey   string    `json:"public_key"`
	Fingerprint string    `json:"fingerprint"`
}

func (q *Queries) CreateUserSSHKey(ctx context.Context, arg CreateUserSSHKeyParams) (UserSshKey, error) {
	row := q.db.QueryRow(ctx, createUserSSHKey,
		arg.UserID,
		arg.Label,
		arg.PublicKey,
		arg.Fingerprint,
	)
	var i UserSshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteUserSSHKey = `-- name: DeleteUserSSHKey :exec
DELETE FROM user_ssh_keys
WHERE id = $1 AND user_id = $2
`

type DeleteUserSSHKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserSSHKey(ctx context.Context, arg DeleteUserSSHKeyParams) error {
	_, err := q.db.Exec(ctx, deleteUserSSHKey, arg.ID, arg.UserID)
	return err
}

const getUserSSHKey = `-- name: GetUserSSHKey :one
SELECT id, user_id, label, public_key, fingerprint, created_at, last_used_at FROM user_ssh_keys
WHERE id = $1 AND user_id = $2
`

type GetUserSSHKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserSSHKey(ctx context.Context, arg GetUserSSHKeyParams) (UserSshKey, error) {
	row := q.db.QueryRow(ctx, getUserSSHKey, arg.ID, arg.UserID)
	var i UserSshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listUserSSHKeys = `-- name: ListUserSSHKeys :many
SELECT id, user_id, label, public_key, fingerprint, created_at, last_used_at FROM user_ssh_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserSSHKeys(ctx context.Context, userID uuid.UUID) ([]UserSshKey, error) {
	rows, err := q.db.Query(ctx, listUserSSHKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSshKey{}
	for rows.Next() {
		var i UserSshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.PublicKey,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupSessionMemberKeyByFingerprint = `-- name: LookupSessionMemberKeyByFingerprint :one
SELECT k.id, k.user_id, k.label, k.public_key, k.fingerprint, k.created_at, k.last_used_at
FROM user_ssh_keys k
JOIN session_members sm ON sm.user_id = k.user_id
WHERE sm.session_id = $1
  AND k.fingerprint = $2
`

type LookupSessionMemberKeyByFingerprintParams struct {
	SessionID   uuid.UUID `json:"session_id"`
	Fingerprint string    `json:"fingerprint"`
}

func (q *Queries) LookupSessionMemberKeyByFingerprint(ctx context.Context, arg LookupSessionMemberKeyByFingerprintParams) (UserSshKey, error) {
	row := q.db.QueryRow(ctx, lookupSessionMemberKeyByFingerprint, arg.SessionID, arg.Fingerprint)
	var i UserSshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchUserSSHKeyLastUsed = `-- name: TouchUserSSHKeyLastUsed :exec
UPDATE user_ssh_keys
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchUserSSHKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserSSHKeyLastUsed, id)
	return err
}
